spring:
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    用上海时区，传递的时间不用做操作，数据库也能和当前一致，而不会少8小时
#    url: jdbc:mysql://localhost:3306/emp?serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/emp?serverTimezone=GMT
    username: root
    password: 123456
# SQL 语句 有没有生成 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
